[package]
name = "rustychain"
version = "0.1.0"
authors = ["gripep"]

[dependencies]
time = "0.1.38"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7.0"